### ISSUE TITLE
Masquer la section de filtres "Auteurs" dans le module propositions

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-angers#1]
Ce qu'on a maintenant: 
<img width="941" alt="capture d ecran 2018-01-03 a 19 26 50" src="https://user-images.githubusercontent.com/11473995/34533846-4015e1c8-f0bc-11e7-9a47-e18d13f1cf95.png">

Ce qu'ils voudraient:
<img width="941" alt="capture d ecran 2018-01-03 a 19 27 22" src="https://user-images.githubusercontent.com/11473995/34533857-488e9e80-f0bc-11e7-8193-78106bd5becf.png">

**Comment by virgile-dev** [comment]
créer un flag dans la config pour cacher ce jeux de filtre.

**Comment by virgile-dev** [comment]
@netbe à faire sur le repo principal en attendant que @ludivinecp mette à jour le repo.

**Comment by netbe** [comment]
Deja disponible dans la conifg (ex: http://localhost:3000/admin/participatory_processes/ut-sit/features/9/edit)
**Official proposals enabled**

**Comment by virgile-dev** [comment]
@valentinchaput si tu décoches "Proposition officielle activées" dans la configuration du module proposition l'option de filtre disparait. 

Si tu ne souhaites pas désactiver les propositions officielles tu peux également cacher le filtre en utilisant cette petite css custom que tu places dans le header snippet :

/* Cacher formulaire Auteurs */
form.new_filter div.filters__section:nth-child(3) {
	display:none;
}
