### ISSUE TITLE
Bugs with internet explorer

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-angers#10]
Titles are not displayed properly on Internet Explorer, which is used by a majority of the Angers audience.
Is it possible to do something about it ?
@moustachu 

![image001](https://user-images.githubusercontent.com/29771726/35284023-0b168736-005a-11e8-82dd-0d24af8ef790.jpg)
![image002](https://user-images.githubusercontent.com/29771726/35284025-0dd22534-005a-11e8-91b3-fccc420ba117.jpg)

**Comment by moustachu** [comment]
Should be fixed with 93fa93cb41450885d9d5203c42b1546cec64f2bd

![bs_win10_ie_11 0](https://user-images.githubusercontent.com/464350/35284546-664f5a5a-005b-11e8-8b3b-7298d6e52865.jpg)

**Comment by valentinchaput** [comment]
Our problem comes from Internet Explorer 11. We wait for the call, but our client might ask for a reverse change to Source Sans Pro.
