### ISSUE TITLE
New trad only for Angers

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-angers#9]
- [x]   Dans les pages "Le processus" : "Documents connexes" à changer en "Documents à consulter" dans Decidim > decidim-core > config > locales > fr.yml

- [x]   Barre de navigation et à d'autres endroits :" Processus participatifs" à changer en "Participation en cours" ici + button :
<img width="1067" alt="capture d ecran 2018-01-23 a 16 19 26" src="https://user-images.githubusercontent.com/29771726/35283772-69642844-0059-11e8-9dbe-bbf8f5566067.png">
<img width="1063" alt="capture d ecran 2018-01-23 a 16 18 45" src="https://user-images.githubusercontent.com/29771726/35283775-697bc7c4-0059-11e8-822d-b382f6ff1f3e.png">

- [x] Périmètre d'application => espace d'organisation  : devient Périmètre concerné

- [x] Comment ets il décidé : devient "mode de décision"
from @valentinchaput

**Comment by valentinchaput** [comment]
Another one, that we should change on every platform: from "plate-forme" to "plateforme" on the sign in page (+ everywhere else on the platform). 

<img width="384" alt="capture d ecran 2018-01-25 a 14 01 13" src="https://user-images.githubusercontent.com/10398564/35389506-3dec3af0-01d8-11e8-9b36-de6400173239.png">
